services:
  telegram-bot:
    build: .
    restart: unless-stopped
    container_name: telegram-bot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - TMDB_API_KEY=${TMDB_API_KEY}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
  